CREATE TABLE public.moves (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    game_id UUID REFERENCES public.games(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    move_order INT NOT NULL,
    move VARCHAR(10) NOT NULL,
    fen VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);