CREATE TABLE public.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    username VARCHAR(150) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);